FROM openjdk:24-slim AS builder

WORKDIR /app

COPY build/libs/syukainvest-0.0.1-SNAPSHOT.jar app.jar

FROM openjdk:24-slim

WORKDIR /app

ENV TZ=Asia/Seoul

COPY --from=builder /app/app.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]